import React, { useEffect, useMemo, useState } from "react";
import {
  ActivityIndicator,
  Platform,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import { Feather } from "@expo/vector-icons";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import journalApi from "../../api/journalApi";
import { useTheme } from "../../context/ThemeContext";

// ─── Helpers ──────────────────────────────────────────────────────────────────

// ─ Mirrors web getLocalDateString() ─────────────────────────────────────────────────────────────────────────────────
const getLocalDateString = (date = new Date()) => {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
};

// Mirrors web buildJournalFilename() — safe kebab-case title + creation date
const buildJournalFilename = (title, dateString) => {
  const safeTitle = (title || "journal-entry")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
  return `${safeTitle || "journal-entry"}-${dateString || getLocalDateString()}.pdf`;
};

const formatDate = (dateString) => {
  if (!dateString) return new Date().toLocaleString();
  return new Date(dateString).toLocaleString();
};

const estimateReadTime = (content) => {
  const words = String(content || "").trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 200)) || 1;
};

const buildJournalHtml = (entry) => `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <style>
    body {
      font-family: Georgia, serif;
      padding: 40px 48px;
      color: #0F172A;
      max-width: 700px;
      margin: 0 auto;
      line-height: 1.7;
    }
    h1 { font-size: 28px; margin-bottom: 6px; color: #0F172A; }
    .meta { font-size: 13px; color: #64748B; margin-bottom: 24px; }
    .mood-badge {
      display: inline-block;
      background: #DBEAFE;
      color: #1D4ED8;
      border-radius: 999px;
      padding: 3px 12px;
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 0.5px;
      text-transform: uppercase;
      margin-bottom: 20px;
    }
    hr { border: none; border-top: 1px solid #E2E8F0; margin: 24px 0; }
    .content { font-size: 15px; white-space: pre-wrap; }
    .insight {
      margin-top: 28px;
      background: #F0F9FF;
      border-left: 4px solid #2563EB;
      padding: 14px 18px;
      border-radius: 6px;
      font-size: 13px;
      color: #1E40AF;
      font-style: italic;
    }
    .insight-label { font-weight: 700; font-style: normal; margin-bottom: 6px; display: block; }
    .footer { margin-top: 40px; font-size: 11px; color: #94A3B8; text-align: center; }
  </style>
</head>
<body>
  <h1>${entry?.title || "Untitled Entry"}</h1>
  <div class="meta">
    ${formatDate(entry?.createdAt)} &nbsp;·&nbsp; ${estimateReadTime(entry?.content)} min read
  </div>
  ${entry?.mood ? `<span class="mood-badge">${String(entry.mood).toUpperCase()}</span>` : ""}
  <hr />
  <div class="content">${String(entry?.content || "No content.").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
  ${
    entry?.aiInsight?.summary
      ? `<div class="insight">
           <span class="insight-label">✦ AI Insight</span>
           ${String(entry.aiInsight.summary).replace(/</g, "&lt;")}
         </div>`
      : ""
  }
  <div class="footer">Generated by SeraniAI · ${new Date().toLocaleDateString()}</div>
</body>
</html>
`;

// ─── Main Screen ──────────────────────────────────────────────────────────────

export const AddJournalScreen = ({ navigation, route }) => {
  const { colors } = useTheme();
  const params = route?.params || {};
  const mode = params.mode || "add";
  const entry = params.entry || null;
  const readOnly = mode === "view";

  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [saving, setSaving] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [refreshingInsight, setRefreshingInsight] = useState(false);
  const [error, setError] = useState("");
  const [journal, setJournal] = useState(entry);

  useEffect(() => {
    const source = entry || {};
    setTitle(source.title || "");
    setContent(source.content || "");
    setJournal(source);
  }, [entry, params.mode]);

  const aiInsight = journal?.aiInsight || null;

  const formattedCreatedAt = useMemo(() => {
    if (!journal?.createdAt) return new Date().toDateString();
    return new Date(journal.createdAt).toLocaleString();
  }, [journal]);

  // ── Save
  const handleSave = async () => {
    if (!title.trim() && !content.trim()) {
      setError("Please add a title or some content.");
      return;
    }
    try {
      setSaving(true);
      setError("");
      const payload = {
        title: title.trim(),
        content: content.trim(),
      };
      const response =
        mode === "edit" && journal?._id
          ? await journalApi.updateJournal(journal._id, payload)
          : await journalApi.createJournal(payload);
      setJournal(response.journal);
      navigation.goBack();
    } catch (saveError) {
      setError(saveError.response?.data?.message || "Failed to save journal entry.");
    } finally {
      setSaving(false);
    }
  };

  // ── Refresh AI insight
  const handleRefreshInsight = async () => {
    if (!journal?._id) return;
    try {
      setRefreshingInsight(true);
      setError("");
      const response = await journalApi.refreshInsight(journal._id);
      if (response?.journal) setJournal(response.journal);
    } catch (refreshError) {
      setError(refreshError.response?.data?.message || "Failed to refresh insight.");
    } finally {
      setRefreshingInsight(false);
    }
  };

  // ── PDF Download — filename mirrors web buildJournalFilename()
  const handleDownloadPDF = async () => {
    try {
      setDownloading(true);
      const html = buildJournalHtml(journal || { title, content });
      const { uri } = await Print.printToFileAsync({ html });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        const filename = buildJournalFilename(
          journal?.title || title,
          journal?.createdAt ? getLocalDateString(new Date(journal.createdAt)) : getLocalDateString()
        );
        await Sharing.shareAsync(uri, {
          mimeType: "application/pdf",
          dialogTitle: filename,
          UTI: "com.adobe.pdf",
        });
      } else {
        setError("Sharing is not available on this device.");
      }
    } catch (pdfError) {
      setError("Failed to generate PDF.");
    } finally {
      setDownloading(false);
    }
  };

  const handleSwitchToEdit = () => {
    navigation.replace("JournalEditor", { mode: "edit", entry: journal });
  };

  // ── Styles (respects safe area)
  const headerPaddingTop =
    Platform.OS === "android" ? (StatusBar.currentHeight || 24) + 12 : 52;

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      {/* ── Header ── */}
      <View
        style={[
          styles.header,
          { backgroundColor: colors.primaryStrong, paddingTop: headerPaddingTop },
        ]}
      >
        <TouchableOpacity style={styles.backButton} onPress={() => navigation.goBack()}>
          <Feather name="arrow-left" size={18} color="#FFFFFF" />
        </TouchableOpacity>

        <View style={{ flex: 1 }}>
          <Text style={styles.headerTitle}>
            {readOnly ? "View Entry" : mode === "edit" ? "Edit Entry" : "New Entry"}
          </Text>
          <Text style={styles.headerSubtitle}>{formattedCreatedAt}</Text>
        </View>

        {/* Right header actions */}
        <View style={styles.headerActions}>
          {/* Download button — shown in all modes when there's a journal */}
          {(readOnly || mode === "edit") && !!journal?._id && (
            <TouchableOpacity
              style={[styles.headerIconBtn, { backgroundColor: "rgba(255,255,255,0.15)" }]}
              onPress={handleDownloadPDF}
              disabled={downloading}
            >
              {downloading ? (
                <ActivityIndicator size="small" color="#FFFFFF" />
              ) : (
                <Feather name="download" size={17} color="#FFFFFF" />
              )}
            </TouchableOpacity>
          )}

          {/* Primary action button */}
          {!readOnly ? (
            <TouchableOpacity
              style={[styles.saveButton, { backgroundColor: colors.surface }]}
              onPress={handleSave}
              disabled={saving}
            >
              {saving ? (
                <ActivityIndicator color={colors.primary} />
              ) : (
                <Text style={[styles.saveButtonText, { color: colors.primary }]}>
                  {mode === "edit" ? "Update" : "Save"}
                </Text>
              )}
            </TouchableOpacity>
          ) : (
            <TouchableOpacity
              style={[styles.saveButton, { backgroundColor: colors.surface }]}
              onPress={handleSwitchToEdit}
            >
              <Text style={[styles.saveButtonText, { color: colors.primary }]}>Edit</Text>
            </TouchableOpacity>
          )}
        </View>
      </View>

      {/* ── Error ── */}
      {!!error && (
        <View
          style={[
            styles.errorBox,
            { backgroundColor: colors.warningBg, borderColor: colors.warningBorder },
          ]}
        >
          <Text style={[styles.errorText, { color: colors.text }]}>{error}</Text>
        </View>
      )}

      {/* ── Content ── */}
      <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
        <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>
          {/* Title */}
          <Text style={[styles.label, { color: colors.muted }]}>Title</Text>
          <TextInput
            value={title}
            onChangeText={setTitle}
            editable={!readOnly}
            placeholder="Entry title"
            placeholderTextColor={colors.muted}
            style={[
              styles.input,
              { color: colors.text, borderColor: colors.border, backgroundColor: colors.inputBg },
            ]}
          />

          {/* Content */}
          <Text style={[styles.label, { color: colors.muted }]}>Journal entry</Text>
          <TextInput
            value={content}
            onChangeText={setContent}
            editable={!readOnly}
            placeholder="Write your thoughts here..."
            placeholderTextColor={colors.muted}
            multiline
            textAlignVertical="top"
            style={[
              styles.textArea,
              { color: colors.text, borderColor: colors.border, backgroundColor: colors.inputBg },
            ]}
          />
        </View>

        {/* ── AI Insight (view-only, read-only display) ── */}
        {!!aiInsight && readOnly && (
          <View
            style={[styles.insightCard, { backgroundColor: colors.surface, borderColor: colors.border }]}
          >
            <View style={styles.insightHeader}>
              <View style={styles.insightTitleRow}>
                <Feather name="sparkles" size={16} color={colors.primary} />
                <Text style={[styles.insightTitle, { color: colors.text }]}>AI Insight</Text>
              </View>
              {!!journal?._id && (
                <TouchableOpacity
                  onPress={handleRefreshInsight}
                  style={[styles.refreshButton, { backgroundColor: colors.inputBg }]}
                  disabled={refreshingInsight}
                >
                  {refreshingInsight ? (
                    <ActivityIndicator size="small" color={colors.primary} />
                  ) : (
                    <Text style={[styles.refreshText, { color: colors.primary }]}>Refresh</Text>
                  )}
                </TouchableOpacity>
              )}
            </View>

            <Text style={[styles.insightText, { color: colors.text }]}>
              {aiInsight.summary || "No insight summary yet."}
            </Text>
            {!!aiInsight.emotionalTone && (
              <Text style={[styles.suggestedText, { color: colors.muted }]}>
                Tone: {aiInsight.emotionalTone}
              </Text>
            )}
            {!!aiInsight.suggestedAction && (
              <Text style={[styles.suggestedText, { color: colors.muted }]}>
                Suggested action: {aiInsight.suggestedAction}
              </Text>
            )}
          </View>
        )}

        {readOnly && (
          <View style={styles.readOnlyNotice}>
            <Text style={[styles.readOnlyText, { color: colors.muted }]}>
              This entry is read-only. Use Edit to make changes.
            </Text>
          </View>
        )}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 18,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: { fontSize: 22, fontWeight: "800", color: "#FFFFFF" },
  headerSubtitle: { marginTop: 3, fontSize: 12, color: "rgba(255,255,255,0.70)" },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  saveButton: {
    minWidth: 76,
    height: 38,
    borderRadius: 19,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  saveButtonText: { fontSize: 14, fontWeight: "800" },
  errorBox: {
    borderWidth: 1,
    borderRadius: 16,
    marginHorizontal: 16,
    marginTop: 14,
    padding: 14,
  },
  errorText: { fontSize: 13, fontWeight: "600" },
  content: {
    padding: 16,
    paddingBottom: 36,
  },
  card: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
  },
  label: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    marginTop: 12,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  textArea: {
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
    minHeight: 240,
  },
  insightCard: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
    marginTop: 14,
  },
  insightHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  insightTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  insightTitle: { fontSize: 16, fontWeight: "800" },
  refreshButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  refreshText: { fontSize: 12, fontWeight: "800" },
  insightText: { marginTop: 12, fontSize: 14, lineHeight: 20 },
  suggestedText: { marginTop: 10, fontSize: 13, lineHeight: 19 },
  readOnlyNotice: {
    marginTop: 14,
    alignItems: "center",
  },
  readOnlyText: { fontSize: 12, fontWeight: "700" },
});

export default AddJournalScreen;